<?php

/**
 * This file is generated by architect.
 */

namespace App\Endpoints\Shops\v1;

use App\UseCase\Command\VirtualGroupsGeneration\VirtualGroupsGenerationCommand;
use Test\PhpServicesBundle\Bus\MessengerBus;
use Test\PhpServicesBundle\GrpcAttributes\GrpcService;
use OpenApi\Attributes\JsonContent;
use OpenApi\Attributes\RequestBody;
use OpenApi\Attributes\Response;
use ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGenerateVirtualGroupsAbstractEndpoint;
use ShopGroups\Shops\v1\GenerateVirtualGroupsRequest;
use ShopGroups\Shops\v1\GenerateVirtualGroupsResponse;
use Symfony\Component\Routing\Annotation\Route;

class ShopGroupGenerateVirtualGroupsEndpoint extends ShopGroupGenerateVirtualGroupsAbstractEndpoint
{
    public function __construct(
        private readonly MessengerBus $busManager,
    ) {
    }

    #[Route('/api/v1/generate_virtual_groups', name: 'generate-virtual-groups', methods: ['POST'])]
    #[GrpcService]
    #[RequestBody(content: new JsonContent(example: '{"IsImportOnlyVirtualGroups":false}'))]
    #[Response(response: 200, description: 'OK', content: new JsonContent(example: '{}'))]
    #[Response(
        response: 422,
        description: '',
        content: new JsonContent(example: '{"title":"Validation Error","detail":["some field is incorrect","some field is incorrect also"]}'),
    )]
    protected function run(GenerateVirtualGroupsRequest $dto): GenerateVirtualGroupsResponse
    {
        $this->busManager->executeAsync(new VirtualGroupsGenerationCommand($dto->getIsImportOnlyVirtualGroups()));

        return new GenerateVirtualGroupsResponse();
    }
}
