replicaCount: 1

env:
  URL_ADDRESS: url"
  URL_CONNECT_TIMEOUT: 10
  URL_TIMEOUT: 5
  API_PASSWORD: [STORE_IN_VAULT]
  APP_ENV: dev
  APP_DEBUG: false

  MIN_DISTR_IOS_VERSION: 8.12.0
  MIN_DISTR_ANDROID_VERSION: 8.12.0

migrations:
  command:
    - bash
    - -c
    - |
      "make migrate-native"

resources:
  limits:
    memory: "500Mi"
    cpu: null
  requests:
    memory: "500Mi"
    cpu: "500m"

cronjobs:
  - schedule: "0 0 * * *" # utc time!
    enabled: true
    name: "url-virtual-groups-import"
    command:
      - sh
      - -c
      - "exec php bin/console app:url-virtual-groups-import --import_only_virtual_groups"
    resources:
      limits:
        memory: "500Mi"
        cpu: "200m"
      requests:
        memory: "500Mi"
        cpu: "200m"
