<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/ecom.shop_group_service.v1.proto

namespace ShopGroups\Shops\v1\GetShopGroupByShopGroupCodeResponse;

/**
 * Protobuf type <code>ecom.shop_group_service.v1.GetShopGroupByShopGroupCodeResponse.ERR_INFO_REASON</code>
 */
class ERR_INFO_REASON
{
    /**
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>VALIDATION_ERROR = 1;</code>
     */
    const VALIDATION_ERROR = 1;
    /**
     * Generated from protobuf enum <code>NOT_FOUND_ERROR = 2;</code>
     */
    const NOT_FOUND_ERROR = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ERR_INFO_REASON::class, \ShopGroups\Shops\v1\GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON::class);

