<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\HttpClientErrorObjects;

class UnprocessableEntityException extends AbstractShopGroupsHttpClientException
{
	public int $httpCode = 422;
	public string $title;
	public array $detail;
}
