<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\HttpClientErrorObjects;

class UnresolvedRequestException extends AbstractShopGroupsHttpClientException
{
	public int $httpCode;
	public mixed $error;
}
