<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: v1/echo.v1.proto

namespace ShopGroups\EchoService\v1;

use Spiral\RoadRunner\GRPC;

interface EchoServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "echo.v1.EchoService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param EchoRequest $in
    * @return EchoResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function EchoMethod(GRPC\ContextInterface $ctx, EchoRequest $in): EchoResponse;
}
