<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\EchoService\v1;

use Spiral\RoadRunner\GRPC\ContextInterface;

class EchoServiceGrpcClient implements EchoServiceInterface
{
    private EchoServiceClient $client;


    public function __construct(EchoServiceClient $client)
    {
        $this->client = $client;
    }


    public function EchoMethod(ContextInterface $ctx, EchoRequest $in): EchoResponse
    {
        return $this->client->EchoMethod($in, $ctx)[1];
    }
}
