version: "3.8"

services:

  kafka:
    image: bitnami/kafka
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - ${KAFKA_UI_PORT}:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
