version: '3.8'

services:
  db:
    image: postgres:15
    hostname: db
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - default

  test-db:
    image: postgres:15
    hostname: test-db
    ports:
      - ${POSTGRES_TEST_PORT}:5432
    environment:
      POSTGRES_DB: application_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - default