<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\Shops\v1;

/**
 * Generated from protobuf message <code>ecom.shop_group_service.v1.AllShopGroup</code>
 */
class AllShopGroup extends \Google\Protobuf\Internal\Message implements \JsonSerializable
{
	/** Generated from protobuf field <code>string code = 1;</code> */
	private $code = '';

	/** Generated from protobuf field <code>bool isActive = 2;</code> */
	private $isActive = false;

	/** Generated from protobuf field <code>bool isDistr = 3;</code> */
	private $isDistr = false;

	/** @var string[]|\Google\Protobuf\Internal\RepeatedField shopCodes */
	private $shopCodes;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     //type string $code
	 *     //type bool $isActive
	 *     //type bool $isDistr
	 *     //type string[]|\Google\Protobuf\Internal\RepeatedField $shopCodes
	 * }
	 */
	public function __construct($data = NULL)
	{
		Meta\EcomShopGroupServiceV1::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string code = 1;</code>
	 * @return string
	 */
	public function getCode()
	{
		return $this->code;
	}


	/**
	 * Generated from protobuf field <code>string code = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setCode($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->code = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>bool isActive = 2;</code>
	 * @return bool
	 */
	public function getIsActive()
	{
		return $this->isActive;
	}


	/**
	 * Generated from protobuf field <code>bool isActive = 2;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setIsActive($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkBool($var);
		$this->isActive = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>bool isDistr = 3;</code>
	 * @return bool
	 */
	public function getIsDistr()
	{
		return $this->isDistr;
	}


	/**
	 * Generated from protobuf field <code>bool isDistr = 3;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setIsDistr($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkBool($var);
		$this->isDistr = $var;

		return $this;
	}


	/**
	 * @return string[]|\Google\Protobuf\Internal\RepeatedField
	 */
	public function getShopCodes(): array|\Google\Protobuf\Internal\RepeatedField
	{
		return $this->shopCodes;
	}


	/**
	 * Generated from protobuf field <code>repeated string shopCodes = 4;</code>
	 * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setShopCodes(array|\Google\Protobuf\Internal\RepeatedField $var)
	{
		$arr = \Google\Protobuf\Internal\GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
		$this->shopCodes = $arr;

		return $this;
	}


	/**
	 * This method created only for OA doc generation
	 */
	public function jsonSerialize(): mixed
	{
		$result = [];
		if (is_object($this->getCode()) && method_exists($this->getCode(), 'jsonSerialize')) {
		                        $result['code'] = $this->getCode()->jsonSerialize();
		                    } else {
		                        $result['code'] = $this->getCode();
		                    }if (is_object($this->getIsActive()) && method_exists($this->getIsActive(), 'jsonSerialize')) {
		                        $result['isActive'] = $this->getIsActive()->jsonSerialize();
		                    } else {
		                        $result['isActive'] = $this->getIsActive();
		                    }if (is_object($this->getIsDistr()) && method_exists($this->getIsDistr(), 'jsonSerialize')) {
		                        $result['isDistr'] = $this->getIsDistr()->jsonSerialize();
		                    } else {
		                        $result['isDistr'] = $this->getIsDistr();
		                    }if (($this->getShopCodes()->count())==0) {
		   $createdArray = [
		       "str1",
		       "str2"
		    ];
		$this->setshopCodes($createdArray);
		}
		foreach ($this->getShopCodes() as $item) {
		   if (is_object($item) && method_exists($item, 'jsonSerialize')) {
		        $result['shopCodes'][] = $item->jsonSerialize();
		    } else {
		        $result['shopCodes'][] = $item;
		    }
		}return $result;
	}
}
