<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\Shops\v1;

/**
 * Generated from protobuf message <code>ecom.shop_group_service.v1.GenerateVirtualGroupsRequest</code>
 */
class GenerateVirtualGroupsRequest extends \Google\Protobuf\Internal\Message implements \JsonSerializable
{
	/** Generated from protobuf field <code>bool IsImportOnlyVirtualGroups = 1;</code> */
	private $IsImportOnlyVirtualGroups = false;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     //type bool $IsImportOnlyVirtualGroups
	 * }
	 */
	public function __construct($data = NULL)
	{
		Meta\EcomShopGroupServiceV1::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>bool IsImportOnlyVirtualGroups = 1;</code>
	 * @return bool
	 */
	public function getIsImportOnlyVirtualGroups()
	{
		return $this->IsImportOnlyVirtualGroups;
	}


	/**
	 * Generated from protobuf field <code>bool IsImportOnlyVirtualGroups = 1;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setIsImportOnlyVirtualGroups($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkBool($var);
		$this->IsImportOnlyVirtualGroups = $var;

		return $this;
	}


	/**
	 * This method created only for OA doc generation
	 */
	public function jsonSerialize(): mixed
	{
		$result = [];
		if (is_object($this->getIsImportOnlyVirtualGroups()) && method_exists($this->getIsImportOnlyVirtualGroups(), 'jsonSerialize')) {
		                        $result['IsImportOnlyVirtualGroups'] = $this->getIsImportOnlyVirtualGroups()->jsonSerialize();
		                    } else {
		                        $result['IsImportOnlyVirtualGroups'] = $this->getIsImportOnlyVirtualGroups();
		                    }return $result;
	}
}
