<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\Shops\v1;

/**
 * Generated from protobuf message <code>ecom.shop_group_service.v1.GetAllShopGroupsRequest</code>
 */
class GetAllShopGroupsRequest extends \Google\Protobuf\Internal\Message implements \JsonSerializable
{
	/** Generated from protobuf field <code>bool isShopGroupActive = 1;</code> */
	private $isShopGroupActive = false;

	/** Generated from protobuf field <code>string lastShopGroupCode = 2;</code> */
	private $lastShopGroupCode = '';

	/** Generated from protobuf field <code>int32 limit = 3;</code> */
	private $limit = 0;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     //type bool $isShopGroupActive
	 *     //type string $lastShopGroupCode
	 *     //type int $limit
	 * }
	 */
	public function __construct($data = NULL)
	{
		Meta\EcomShopGroupServiceV1::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>bool isShopGroupActive = 1;</code>
	 * @return bool
	 */
	public function getIsShopGroupActive()
	{
		return $this->isShopGroupActive;
	}


	/**
	 * Generated from protobuf field <code>bool isShopGroupActive = 1;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setIsShopGroupActive($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkBool($var);
		$this->isShopGroupActive = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string lastShopGroupCode = 2;</code>
	 * @return string
	 */
	public function getLastShopGroupCode()
	{
		return $this->lastShopGroupCode;
	}


	/**
	 * Generated from protobuf field <code>string lastShopGroupCode = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setLastShopGroupCode($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->lastShopGroupCode = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>int32 limit = 3;</code>
	 * @return int
	 */
	public function getLimit()
	{
		return $this->limit;
	}


	/**
	 * Generated from protobuf field <code>int32 limit = 3;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setLimit($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkInt32($var);
		$this->limit = $var;

		return $this;
	}


	/**
	 * This method created only for OA doc generation
	 */
	public function jsonSerialize(): mixed
	{
		$result = [];
		if (is_object($this->getIsShopGroupActive()) && method_exists($this->getIsShopGroupActive(), 'jsonSerialize')) {
		                        $result['isShopGroupActive'] = $this->getIsShopGroupActive()->jsonSerialize();
		                    } else {
		                        $result['isShopGroupActive'] = $this->getIsShopGroupActive();
		                    }if (is_object($this->getLastShopGroupCode()) && method_exists($this->getLastShopGroupCode(), 'jsonSerialize')) {
		                        $result['lastShopGroupCode'] = $this->getLastShopGroupCode()->jsonSerialize();
		                    } else {
		                        $result['lastShopGroupCode'] = $this->getLastShopGroupCode();
		                    }if (is_object($this->getLimit()) && method_exists($this->getLimit(), 'jsonSerialize')) {
		                        $result['limit'] = $this->getLimit()->jsonSerialize();
		                    } else {
		                        $result['limit'] = $this->getLimit();
		                    }return $result;
	}
}
