<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\Shops\v1;

/**
 * Generated from protobuf message <code>ecom.shop_group_service.v1.GetConsumerShopsRequest</code>
 */
class GetConsumerShopsRequest extends \Google\Protobuf\Internal\Message implements \JsonSerializable
{
	/** Generated from protobuf field <code>string ConsumerCode = 1;</code> */
	private $ConsumerCode = '';

	/** Generated from protobuf field <code>string ShopGroupCode = 2;</code> */
	private $ShopGroupCode = '';

	/** Generated from protobuf field <code>bool Recursive = 3;</code> */
	private $Recursive = false;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     //type string $ConsumerCode
	 *     //type string $ShopGroupCode
	 *     //type bool $Recursive
	 * }
	 */
	public function __construct($data = NULL)
	{
		Meta\EcomShopGroupServiceV1::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string ConsumerCode = 1;</code>
	 * @return string
	 */
	public function getConsumerCode()
	{
		return $this->ConsumerCode;
	}


	/**
	 * Generated from protobuf field <code>string ConsumerCode = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setConsumerCode($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->ConsumerCode = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string ShopGroupCode = 2;</code>
	 * @return string
	 */
	public function getShopGroupCode()
	{
		return $this->ShopGroupCode;
	}


	/**
	 * Generated from protobuf field <code>string ShopGroupCode = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setShopGroupCode($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->ShopGroupCode = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>bool Recursive = 3;</code>
	 * @return bool
	 */
	public function getRecursive()
	{
		return $this->Recursive;
	}


	/**
	 * Generated from protobuf field <code>bool Recursive = 3;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setRecursive($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkBool($var);
		$this->Recursive = $var;

		return $this;
	}


	/**
	 * This method created only for OA doc generation
	 */
	public function jsonSerialize(): mixed
	{
		$result = [];
		if (is_object($this->getConsumerCode()) && method_exists($this->getConsumerCode(), 'jsonSerialize')) {
		                        $result['ConsumerCode'] = $this->getConsumerCode()->jsonSerialize();
		                    } else {
		                        $result['ConsumerCode'] = $this->getConsumerCode();
		                    }if (is_object($this->getShopGroupCode()) && method_exists($this->getShopGroupCode(), 'jsonSerialize')) {
		                        $result['ShopGroupCode'] = $this->getShopGroupCode()->jsonSerialize();
		                    } else {
		                        $result['ShopGroupCode'] = $this->getShopGroupCode();
		                    }if (is_object($this->getRecursive()) && method_exists($this->getRecursive(), 'jsonSerialize')) {
		                        $result['Recursive'] = $this->getRecursive()->jsonSerialize();
		                    } else {
		                        $result['Recursive'] = $this->getRecursive();
		                    }return $result;
	}
}
