<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\Shops\v1;

/**
 * Generated from protobuf message <code>ecom.shop_group_service.v1.GetFailedMessagesResponse</code>
 */
class GetFailedMessagesResponse extends \Google\Protobuf\Internal\Message implements \JsonSerializable
{
	/**
	 * Int32Value используется, что Google Protobuf не затирал нулевые значения
	 *
	 * Generated from protobuf field <code>.google.protobuf.Int32Value CountRemaining = 1;</code>
	 */
	private $CountRemaining = null;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     //type \Google\Protobuf\Int32Value $CountRemaining
	 *           Int32Value используется, что Google Protobuf не затирал нулевые значения
	 * }
	 */
	public function __construct($data = NULL)
	{
		Meta\EcomShopGroupServiceV1::initOnce();
		parent::__construct($data);
	}


	/**
	 * Int32Value используется, что Google Protobuf не затирал нулевые значения
	 *
	 * Generated from protobuf field <code>.google.protobuf.Int32Value CountRemaining = 1;</code>
	 * @return \Google\Protobuf\Int32Value
	 */
	public function getCountRemaining()
	{
		return $this->CountRemaining;
	}


	/**
	 * Int32Value используется, что Google Protobuf не затирал нулевые значения
	 *
	 * Generated from protobuf field <code>.google.protobuf.Int32Value CountRemaining = 1;</code>
	 * @param \Google\Protobuf\Int32Value $var
	 * @return $this
	 */
	public function setCountRemaining($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
		$this->CountRemaining = $var;

		return $this;
	}


	/**
	 * This method created only for OA doc generation
	 */
	public function jsonSerialize(): mixed
	{
		$result = [];
		if (is_object($this->getCountRemaining()) && method_exists($this->getCountRemaining(), 'jsonSerialize')) {
		                        $result['CountRemaining'] = $this->getCountRemaining()->jsonSerialize();
		                    } else {
		                        $result['CountRemaining'] = $this->getCountRemaining();
		                    }return $result;
	}
}
