<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/ecom.shop_group_service.v1.proto

namespace ShopGroups\Shops\v1;

if (false) {
    /**
     * This class is deprecated. Use ShopGroups\Shops\v1\GetShopGroupByShopGroupCodeResponse\ERR_INFO_REASON instead.
     * @deprecated
     */
    class GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON {}
}
class_exists(GetShopGroupByShopGroupCodeResponse\ERR_INFO_REASON::class);
@trigger_error('ShopGroups\Shops\v1\GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON is deprecated and will be removed in the next major release. Use ShopGroups\Shops\v1\GetShopGroupByShopGroupCodeResponse\ERR_INFO_REASON instead', E_USER_DEPRECATED);

