<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\Shops\v1;

/**
 * Generated from protobuf message <code>ecom.shop_group_service.v1.GetShopsRequest</code>
 */
class GetShopsRequest extends \Google\Protobuf\Internal\Message implements \JsonSerializable
{
	/** Generated from protobuf field <code>string shopGroupCode = 1;</code> */
	private $shopGroupCode = '';


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     //type string $shopGroupCode
	 * }
	 */
	public function __construct($data = NULL)
	{
		Meta\EcomShopGroupServiceV1::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string shopGroupCode = 1;</code>
	 * @return string
	 */
	public function getShopGroupCode()
	{
		return $this->shopGroupCode;
	}


	/**
	 * Generated from protobuf field <code>string shopGroupCode = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setShopGroupCode($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->shopGroupCode = $var;

		return $this;
	}


	/**
	 * This method created only for OA doc generation
	 */
	public function jsonSerialize(): mixed
	{
		$result = [];
		if (is_object($this->getShopGroupCode()) && method_exists($this->getShopGroupCode(), 'jsonSerialize')) {
		                        $result['shopGroupCode'] = $this->getShopGroupCode()->jsonSerialize();
		                    } else {
		                        $result['shopGroupCode'] = $this->getShopGroupCode();
		                    }return $result;
	}
}
