<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\Shops\v1;

/**
 * Generated from protobuf message <code>ecom.shop_group_service.v1.ImportFileRequest</code>
 */
class ImportFileRequest extends \Google\Protobuf\Internal\Message implements \JsonSerializable
{
	/** Generated from protobuf field <code>string ShopGroups = 1;</code> */
	private $ShopGroups = '';

	/** Generated from protobuf field <code>string Consumers = 2;</code> */
	private $Consumers = '';

	/** Generated from protobuf field <code>string ShopsToShopGroups = 3;</code> */
	private $ShopsToShopGroups = '';


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     //type string $ShopGroups
	 *     //type string $Consumers
	 *     //type string $ShopsToShopGroups
	 * }
	 */
	public function __construct($data = NULL)
	{
		Meta\EcomShopGroupServiceV1::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string ShopGroups = 1;</code>
	 * @return string
	 */
	public function getShopGroups()
	{
		return $this->ShopGroups;
	}


	/**
	 * Generated from protobuf field <code>string ShopGroups = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setShopGroups($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->ShopGroups = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string Consumers = 2;</code>
	 * @return string
	 */
	public function getConsumers()
	{
		return $this->Consumers;
	}


	/**
	 * Generated from protobuf field <code>string Consumers = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setConsumers($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->Consumers = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string ShopsToShopGroups = 3;</code>
	 * @return string
	 */
	public function getShopsToShopGroups()
	{
		return $this->ShopsToShopGroups;
	}


	/**
	 * Generated from protobuf field <code>string ShopsToShopGroups = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setShopsToShopGroups($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->ShopsToShopGroups = $var;

		return $this;
	}


	/**
	 * This method created only for OA doc generation
	 */
	public function jsonSerialize(): mixed
	{
		$result = [];
		if (is_object($this->getShopGroups()) && method_exists($this->getShopGroups(), 'jsonSerialize')) {
		                        $result['ShopGroups'] = $this->getShopGroups()->jsonSerialize();
		                    } else {
		                        $result['ShopGroups'] = $this->getShopGroups();
		                    }if (is_object($this->getConsumers()) && method_exists($this->getConsumers(), 'jsonSerialize')) {
		                        $result['Consumers'] = $this->getConsumers()->jsonSerialize();
		                    } else {
		                        $result['Consumers'] = $this->getConsumers();
		                    }if (is_object($this->getShopsToShopGroups()) && method_exists($this->getShopsToShopGroups(), 'jsonSerialize')) {
		                        $result['ShopsToShopGroups'] = $this->getShopsToShopGroups()->jsonSerialize();
		                    } else {
		                        $result['ShopsToShopGroups'] = $this->getShopsToShopGroups();
		                    }return $result;
	}
}
