<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\Shops\v1;

/**
 * Generated from protobuf message <code>ecom.shop_group_service.v1.ShopModel</code>
 */
class ShopModel extends \Google\Protobuf\Internal\Message implements \JsonSerializable
{
	/** Generated from protobuf field <code>string code = 1;</code> */
	private $code = '';


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     //type string $code
	 * }
	 */
	public function __construct($data = NULL)
	{
		Meta\EcomShopGroupServiceV1::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string code = 1;</code>
	 * @return string
	 */
	public function getCode()
	{
		return $this->code;
	}


	/**
	 * Generated from protobuf field <code>string code = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setCode($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->code = $var;

		return $this;
	}


	/**
	 * This method created only for OA doc generation
	 */
	public function jsonSerialize(): mixed
	{
		$result = [];
		if (is_object($this->getCode()) && method_exists($this->getCode(), 'jsonSerialize')) {
		                        $result['code'] = $this->getCode()->jsonSerialize();
		                    } else {
		                        $result['code'] = $this->getCode();
		                    }return $result;
	}
}
