<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\Shops\v1;

/**
 * Generated from protobuf message <code>ecom.shop_group_service.v1.ShopGroupItem</code>
 */
class ShopGroupItem extends \Google\Protobuf\Internal\Message implements \JsonSerializable
{
	/** Generated from protobuf field <code>string Code = 1;</code> */
	private $Code = '';

	/** @var string[]|\Google\Protobuf\Internal\RepeatedField ShopsCodes */
	private $ShopsCodes;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     //type string $Code
	 *     //type string[]|\Google\Protobuf\Internal\RepeatedField $ShopsCodes
	 * }
	 */
	public function __construct($data = NULL)
	{
		Meta\EcomShopGroupServiceV1::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string Code = 1;</code>
	 * @return string
	 */
	public function getCode()
	{
		return $this->Code;
	}


	/**
	 * Generated from protobuf field <code>string Code = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setCode($var)
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->Code = $var;

		return $this;
	}


	/**
	 * @return string[]|\Google\Protobuf\Internal\RepeatedField
	 */
	public function getShopsCodes(): array|\Google\Protobuf\Internal\RepeatedField
	{
		return $this->ShopsCodes;
	}


	/**
	 * Generated from protobuf field <code>repeated string ShopsCodes = 2;</code>
	 * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setShopsCodes(array|\Google\Protobuf\Internal\RepeatedField $var)
	{
		$arr = \Google\Protobuf\Internal\GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
		$this->ShopsCodes = $arr;

		return $this;
	}


	/**
	 * This method created only for OA doc generation
	 */
	public function jsonSerialize(): mixed
	{
		$result = [];
		if (is_object($this->getCode()) && method_exists($this->getCode(), 'jsonSerialize')) {
		                        $result['Code'] = $this->getCode()->jsonSerialize();
		                    } else {
		                        $result['Code'] = $this->getCode();
		                    }if (($this->getShopsCodes()->count())==0) {
		   $createdArray = [
		       "str1",
		       "str2"
		    ];
		$this->setShopsCodes($createdArray);
		}
		foreach ($this->getShopsCodes() as $item) {
		   if (is_object($item) && method_exists($item, 'jsonSerialize')) {
		        $result['ShopsCodes'][] = $item->jsonSerialize();
		    } else {
		        $result['ShopsCodes'][] = $item;
		    }
		}return $result;
	}
}
