<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: v1/ecom.shop_group_service.v1.proto

namespace ShopGroups\Shops\v1;

use Spiral\RoadRunner\GRPC;

interface ShopGroupInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "ecom.shop_group_service.v1.ShopGroup";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetShopGroupByShopCodeRequest $in
    * @return GetShopGroupByShopCodeResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetShopGroupByShopCode(GRPC\ContextInterface $ctx, GetShopGroupByShopCodeRequest $in): GetShopGroupByShopCodeResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetShopGroupByFiasIdRequest $in
    * @return GetShopGroupByFiasIdResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetShopGroupByFiasId(GRPC\ContextInterface $ctx, GetShopGroupByFiasIdRequest $in): GetShopGroupByFiasIdResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetConsumerShopsRequest $in
    * @return ShopGroupsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetConsumerShops(GRPC\ContextInterface $ctx, GetConsumerShopsRequest $in): ShopGroupsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ExportRequest $in
    * @return ExportResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Export(GRPC\ContextInterface $ctx, ExportRequest $in): ExportResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ImportFileRequest $in
    * @return ImportFileResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ImportFile(GRPC\ContextInterface $ctx, ImportFileRequest $in): ImportFileResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GenerateVirtualGroupsRequest $in
    * @return GenerateVirtualGroupsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GenerateVirtualGroups(GRPC\ContextInterface $ctx, GenerateVirtualGroupsRequest $in): GenerateVirtualGroupsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ProcessFailedMessagesRequest $in
    * @return ProcessFailedMessagesResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ProcessFailedMessages(GRPC\ContextInterface $ctx, ProcessFailedMessagesRequest $in): ProcessFailedMessagesResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetFailedMessagesRequest $in
    * @return GetFailedMessagesResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetFailedMessages(GRPC\ContextInterface $ctx, GetFailedMessagesRequest $in): GetFailedMessagesResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetShopGroupsRequest $in
    * @return GetShopGroupsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetShopGroups(GRPC\ContextInterface $ctx, GetShopGroupsRequest $in): GetShopGroupsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetAllShopGroupsRequest $in
    * @return GetAllShopGroupsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetAllShopGroups(GRPC\ContextInterface $ctx, GetAllShopGroupsRequest $in): GetAllShopGroupsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetShopsRequest $in
    * @return GetShopsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetShops(GRPC\ContextInterface $ctx, GetShopsRequest $in): GetShopsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetShopGroupByShopGroupCodeRequest $in
    * @return GetShopGroupByShopGroupCodeResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetShopGroupByShopGroupCode(GRPC\ContextInterface $ctx, GetShopGroupByShopGroupCodeRequest $in): GetShopGroupByShopGroupCodeResponse;
}
