<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\EchoService\v1\InnerGrpcControllers;

final class EchoServiceInnerController implements \ShopGroups\EchoService\v1\EchoServiceInterface
{
	private \Symfony\Component\DependencyInjection\Container $container;


	public function __construct(\Symfony\Component\DependencyInjection\Container $container)
	{
		$this->container = $container;
	}


	public function EchoMethod(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\EchoService\v1\EchoRequest $in,
	): \ShopGroups\EchoService\v1\EchoResponse
	{
		/** @var \ShopGroups\EchoService\v1\AbstractEndpoints\EchoServiceEchoMethodAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\EchoService\v1\AbstractEndpoints\EchoServiceEchoMethodAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}
}
