<?php

/**
 * This file is generated by architect.
 */

namespace ShopGroups\Shops\v1\InnerGrpcControllers;

final class ShopGroupInnerController implements \ShopGroups\Shops\v1\ShopGroupInterface
{
	private \Symfony\Component\DependencyInjection\Container $container;


	public function __construct(\Symfony\Component\DependencyInjection\Container $container)
	{
		$this->container = $container;
	}


	public function GetShopGroupByShopCode(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\Shops\v1\GetShopGroupByShopCodeRequest $in,
	): \ShopGroups\Shops\v1\GetShopGroupByShopCodeResponse
	{
		/** @var \ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetShopGroupByShopCodeAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetShopGroupByShopCodeAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}


	public function GetShopGroupByFiasId(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\Shops\v1\GetShopGroupByFiasIdRequest $in,
	): \ShopGroups\Shops\v1\GetShopGroupByFiasIdResponse
	{
		/** @var \ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetShopGroupByFiasIdAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetShopGroupByFiasIdAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}


	public function GetConsumerShops(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\Shops\v1\GetConsumerShopsRequest $in,
	): \ShopGroups\Shops\v1\ShopGroupsResponse
	{
		/** @var \ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetConsumerShopsAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetConsumerShopsAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}


	public function Export(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\Shops\v1\ExportRequest $in,
	): \ShopGroups\Shops\v1\ExportResponse
	{
		/** @var \ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupExportAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupExportAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}


	public function ImportFile(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\Shops\v1\ImportFileRequest $in,
	): \ShopGroups\Shops\v1\ImportFileResponse
	{
		/** @var \ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupImportFileAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupImportFileAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}


	public function GenerateVirtualGroups(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\Shops\v1\GenerateVirtualGroupsRequest $in,
	): \ShopGroups\Shops\v1\GenerateVirtualGroupsResponse
	{
		/** @var \ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGenerateVirtualGroupsAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGenerateVirtualGroupsAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}


	public function ProcessFailedMessages(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\Shops\v1\ProcessFailedMessagesRequest $in,
	): \ShopGroups\Shops\v1\ProcessFailedMessagesResponse
	{
		/** @var \ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupProcessFailedMessagesAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupProcessFailedMessagesAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}


	public function GetFailedMessages(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\Shops\v1\GetFailedMessagesRequest $in,
	): \ShopGroups\Shops\v1\GetFailedMessagesResponse
	{
		/** @var \ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetFailedMessagesAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetFailedMessagesAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}


	public function GetShopGroups(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\Shops\v1\GetShopGroupsRequest $in,
	): \ShopGroups\Shops\v1\GetShopGroupsResponse
	{
		/** @var \ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetShopGroupsAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetShopGroupsAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}


	public function GetAllShopGroups(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\Shops\v1\GetAllShopGroupsRequest $in,
	): \ShopGroups\Shops\v1\GetAllShopGroupsResponse
	{
		/** @var \ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetAllShopGroupsAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetAllShopGroupsAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}


	public function GetShops(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\Shops\v1\GetShopsRequest $in,
	): \ShopGroups\Shops\v1\GetShopsResponse
	{
		/** @var \ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetShopsAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetShopsAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}


	public function GetShopGroupByShopGroupCode(
		\Spiral\RoadRunner\GRPC\ContextInterface $ctx,
		\ShopGroups\Shops\v1\GetShopGroupByShopGroupCodeRequest $in,
	): \ShopGroups\Shops\v1\GetShopGroupByShopGroupCodeResponse
	{
		/** @var \ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetShopGroupByShopGroupCodeAbstractEndpoint $transportController */
		$transportController = $this->container->get(\ShopGroups\Shops\v1\AbstractEndpoints\ShopGroupGetShopGroupByShopGroupCodeAbstractEndpoint::class);
		$transportController->context = $ctx->getValues();
		return $transportController($in);
	}
}
