// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.6.1
// source: v1/ecom.shop_group_service.v1.proto

package shop_groups_contracts_v1

import (
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShopGroupByFiasIdResponse_ERR_INFO_REASON int32

const (
	GetShopGroupByFiasIdResponse_UNSPECIFIED      GetShopGroupByFiasIdResponse_ERR_INFO_REASON = 0
	GetShopGroupByFiasIdResponse_VALIDATION_ERROR GetShopGroupByFiasIdResponse_ERR_INFO_REASON = 1
	GetShopGroupByFiasIdResponse_NOT_FOUND_ERROR  GetShopGroupByFiasIdResponse_ERR_INFO_REASON = 2
)

// Enum value maps for GetShopGroupByFiasIdResponse_ERR_INFO_REASON.
var (
	GetShopGroupByFiasIdResponse_ERR_INFO_REASON_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "VALIDATION_ERROR",
		2: "NOT_FOUND_ERROR",
	}
	GetShopGroupByFiasIdResponse_ERR_INFO_REASON_value = map[string]int32{
		"UNSPECIFIED":      0,
		"VALIDATION_ERROR": 1,
		"NOT_FOUND_ERROR":  2,
	}
)

func (x GetShopGroupByFiasIdResponse_ERR_INFO_REASON) Enum() *GetShopGroupByFiasIdResponse_ERR_INFO_REASON {
	p := new(GetShopGroupByFiasIdResponse_ERR_INFO_REASON)
	*p = x
	return p
}

func (x GetShopGroupByFiasIdResponse_ERR_INFO_REASON) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetShopGroupByFiasIdResponse_ERR_INFO_REASON) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_ecom_shop_group_service_v1_proto_enumTypes[0].Descriptor()
}

func (GetShopGroupByFiasIdResponse_ERR_INFO_REASON) Type() protoreflect.EnumType {
	return &file_v1_ecom_shop_group_service_v1_proto_enumTypes[0]
}

func (x GetShopGroupByFiasIdResponse_ERR_INFO_REASON) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetShopGroupByFiasIdResponse_ERR_INFO_REASON.Descriptor instead.
func (GetShopGroupByFiasIdResponse_ERR_INFO_REASON) EnumDescriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{3, 0}
}

type GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON int32

const (
	GetShopGroupByShopGroupCodeResponse_UNSPECIFIED      GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON = 0
	GetShopGroupByShopGroupCodeResponse_VALIDATION_ERROR GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON = 1
	GetShopGroupByShopGroupCodeResponse_NOT_FOUND_ERROR  GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON = 2
)

// Enum value maps for GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON.
var (
	GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "VALIDATION_ERROR",
		2: "NOT_FOUND_ERROR",
	}
	GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON_value = map[string]int32{
		"UNSPECIFIED":      0,
		"VALIDATION_ERROR": 1,
		"NOT_FOUND_ERROR":  2,
	}
)

func (x GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON) Enum() *GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON {
	p := new(GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON)
	*p = x
	return p
}

func (x GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_ecom_shop_group_service_v1_proto_enumTypes[1].Descriptor()
}

func (GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON) Type() protoreflect.EnumType {
	return &file_v1_ecom_shop_group_service_v1_proto_enumTypes[1]
}

func (x GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON.Descriptor instead.
func (GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON) EnumDescriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{27, 0}
}

type GetShopGroupByShopCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UfXmlId         string `protobuf:"bytes,1,opt,name=UfXmlId,proto3" json:"UfXmlId,omitempty"`
	ConsumerCode    string `protobuf:"bytes,2,opt,name=ConsumerCode,proto3" json:"ConsumerCode,omitempty"`
	ConsumerVersion string `protobuf:"bytes,3,opt,name=ConsumerVersion,proto3" json:"ConsumerVersion,omitempty"`
}

func (x *GetShopGroupByShopCodeRequest) Reset() {
	*x = GetShopGroupByShopCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopGroupByShopCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopGroupByShopCodeRequest) ProtoMessage() {}

func (x *GetShopGroupByShopCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopGroupByShopCodeRequest.ProtoReflect.Descriptor instead.
func (*GetShopGroupByShopCodeRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{0}
}

func (x *GetShopGroupByShopCodeRequest) GetUfXmlId() string {
	if x != nil {
		return x.UfXmlId
	}
	return ""
}

func (x *GetShopGroupByShopCodeRequest) GetConsumerCode() string {
	if x != nil {
		return x.ConsumerCode
	}
	return ""
}

func (x *GetShopGroupByShopCodeRequest) GetConsumerVersion() string {
	if x != nil {
		return x.ConsumerVersion
	}
	return ""
}

type GetShopGroupByShopCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopGroupCode string `protobuf:"bytes,1,opt,name=ShopGroupCode,proto3" json:"ShopGroupCode,omitempty"`
	Title         string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
}

func (x *GetShopGroupByShopCodeResponse) Reset() {
	*x = GetShopGroupByShopCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopGroupByShopCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopGroupByShopCodeResponse) ProtoMessage() {}

func (x *GetShopGroupByShopCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopGroupByShopCodeResponse.ProtoReflect.Descriptor instead.
func (*GetShopGroupByShopCodeResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{1}
}

func (x *GetShopGroupByShopCodeResponse) GetShopGroupCode() string {
	if x != nil {
		return x.ShopGroupCode
	}
	return ""
}

func (x *GetShopGroupByShopCodeResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetShopGroupByFiasIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FiasId          string `protobuf:"bytes,1,opt,name=FiasId,proto3" json:"FiasId,omitempty"`
	ConsumerCode    string `protobuf:"bytes,2,opt,name=ConsumerCode,proto3" json:"ConsumerCode,omitempty"`
	ConsumerVersion string `protobuf:"bytes,3,opt,name=ConsumerVersion,proto3" json:"ConsumerVersion,omitempty"`
}

func (x *GetShopGroupByFiasIdRequest) Reset() {
	*x = GetShopGroupByFiasIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopGroupByFiasIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopGroupByFiasIdRequest) ProtoMessage() {}

func (x *GetShopGroupByFiasIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopGroupByFiasIdRequest.ProtoReflect.Descriptor instead.
func (*GetShopGroupByFiasIdRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{2}
}

func (x *GetShopGroupByFiasIdRequest) GetFiasId() string {
	if x != nil {
		return x.FiasId
	}
	return ""
}

func (x *GetShopGroupByFiasIdRequest) GetConsumerCode() string {
	if x != nil {
		return x.ConsumerCode
	}
	return ""
}

func (x *GetShopGroupByFiasIdRequest) GetConsumerVersion() string {
	if x != nil {
		return x.ConsumerVersion
	}
	return ""
}

type GetShopGroupByFiasIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopGroupCode string `protobuf:"bytes,1,opt,name=ShopGroupCode,proto3" json:"ShopGroupCode,omitempty"`
	Title         string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
}

func (x *GetShopGroupByFiasIdResponse) Reset() {
	*x = GetShopGroupByFiasIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopGroupByFiasIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopGroupByFiasIdResponse) ProtoMessage() {}

func (x *GetShopGroupByFiasIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopGroupByFiasIdResponse.ProtoReflect.Descriptor instead.
func (*GetShopGroupByFiasIdResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{3}
}

func (x *GetShopGroupByFiasIdResponse) GetShopGroupCode() string {
	if x != nil {
		return x.ShopGroupCode
	}
	return ""
}

func (x *GetShopGroupByFiasIdResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetConsumerShopsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConsumerCode  string `protobuf:"bytes,1,opt,name=ConsumerCode,proto3" json:"ConsumerCode,omitempty"`
	ShopGroupCode string `protobuf:"bytes,2,opt,name=ShopGroupCode,proto3" json:"ShopGroupCode,omitempty"`
	Recursive     bool   `protobuf:"varint,3,opt,name=Recursive,proto3" json:"Recursive,omitempty"`
}

func (x *GetConsumerShopsRequest) Reset() {
	*x = GetConsumerShopsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConsumerShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerShopsRequest) ProtoMessage() {}

func (x *GetConsumerShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerShopsRequest.ProtoReflect.Descriptor instead.
func (*GetConsumerShopsRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{4}
}

func (x *GetConsumerShopsRequest) GetConsumerCode() string {
	if x != nil {
		return x.ConsumerCode
	}
	return ""
}

func (x *GetConsumerShopsRequest) GetShopGroupCode() string {
	if x != nil {
		return x.ShopGroupCode
	}
	return ""
}

func (x *GetConsumerShopsRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type ShopGroupItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	ShopsCodes []string `protobuf:"bytes,2,rep,name=ShopsCodes,proto3" json:"ShopsCodes,omitempty"`
}

func (x *ShopGroupItem) Reset() {
	*x = ShopGroupItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopGroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopGroupItem) ProtoMessage() {}

func (x *ShopGroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopGroupItem.ProtoReflect.Descriptor instead.
func (*ShopGroupItem) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{5}
}

func (x *ShopGroupItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShopGroupItem) GetShopsCodes() []string {
	if x != nil {
		return x.ShopsCodes
	}
	return nil
}

type ShopGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ShopGroupItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *ShopGroupsResponse) Reset() {
	*x = ShopGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopGroupsResponse) ProtoMessage() {}

func (x *ShopGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopGroupsResponse.ProtoReflect.Descriptor instead.
func (*ShopGroupsResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{6}
}

func (x *ShopGroupsResponse) GetItems() []*ShopGroupItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ImportFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopGroups        string `protobuf:"bytes,1,opt,name=ShopGroups,proto3" json:"ShopGroups,omitempty"`
	Consumers         string `protobuf:"bytes,2,opt,name=Consumers,proto3" json:"Consumers,omitempty"`
	ShopsToShopGroups string `protobuf:"bytes,3,opt,name=ShopsToShopGroups,proto3" json:"ShopsToShopGroups,omitempty"`
}

func (x *ImportFileRequest) Reset() {
	*x = ImportFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFileRequest) ProtoMessage() {}

func (x *ImportFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFileRequest.ProtoReflect.Descriptor instead.
func (*ImportFileRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{7}
}

func (x *ImportFileRequest) GetShopGroups() string {
	if x != nil {
		return x.ShopGroups
	}
	return ""
}

func (x *ImportFileRequest) GetConsumers() string {
	if x != nil {
		return x.Consumers
	}
	return ""
}

func (x *ImportFileRequest) GetShopsToShopGroups() string {
	if x != nil {
		return x.ShopsToShopGroups
	}
	return ""
}

type ImportFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImportFileResponse) Reset() {
	*x = ImportFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFileResponse) ProtoMessage() {}

func (x *ImportFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFileResponse.ProtoReflect.Descriptor instead.
func (*ImportFileResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{8}
}

type ExportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{9}
}

type ExportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopGroups        string `protobuf:"bytes,1,opt,name=ShopGroups,proto3" json:"ShopGroups,omitempty"`
	Consumers         string `protobuf:"bytes,2,opt,name=Consumers,proto3" json:"Consumers,omitempty"`
	ShopsToShopGroups string `protobuf:"bytes,3,opt,name=ShopsToShopGroups,proto3" json:"ShopsToShopGroups,omitempty"`
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{10}
}

func (x *ExportResponse) GetShopGroups() string {
	if x != nil {
		return x.ShopGroups
	}
	return ""
}

func (x *ExportResponse) GetConsumers() string {
	if x != nil {
		return x.Consumers
	}
	return ""
}

func (x *ExportResponse) GetShopsToShopGroups() string {
	if x != nil {
		return x.ShopsToShopGroups
	}
	return ""
}

type GenerateVirtualGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsImportOnlyVirtualGroups bool `protobuf:"varint,1,opt,name=IsImportOnlyVirtualGroups,proto3" json:"IsImportOnlyVirtualGroups,omitempty"`
}

func (x *GenerateVirtualGroupsRequest) Reset() {
	*x = GenerateVirtualGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateVirtualGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateVirtualGroupsRequest) ProtoMessage() {}

func (x *GenerateVirtualGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateVirtualGroupsRequest.ProtoReflect.Descriptor instead.
func (*GenerateVirtualGroupsRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateVirtualGroupsRequest) GetIsImportOnlyVirtualGroups() bool {
	if x != nil {
		return x.IsImportOnlyVirtualGroups
	}
	return false
}

type GenerateVirtualGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateVirtualGroupsResponse) Reset() {
	*x = GenerateVirtualGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateVirtualGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateVirtualGroupsResponse) ProtoMessage() {}

func (x *GenerateVirtualGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateVirtualGroupsResponse.ProtoReflect.Descriptor instead.
func (*GenerateVirtualGroupsResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{12}
}

type ProcessFailedMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LimitCount int32 `protobuf:"varint,1,opt,name=LimitCount,proto3" json:"LimitCount,omitempty"`
	LimitTime  int32 `protobuf:"varint,2,opt,name=LimitTime,proto3" json:"LimitTime,omitempty"`
}

func (x *ProcessFailedMessagesRequest) Reset() {
	*x = ProcessFailedMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessFailedMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFailedMessagesRequest) ProtoMessage() {}

func (x *ProcessFailedMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFailedMessagesRequest.ProtoReflect.Descriptor instead.
func (*ProcessFailedMessagesRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{13}
}

func (x *ProcessFailedMessagesRequest) GetLimitCount() int32 {
	if x != nil {
		return x.LimitCount
	}
	return 0
}

func (x *ProcessFailedMessagesRequest) GetLimitTime() int32 {
	if x != nil {
		return x.LimitTime
	}
	return 0
}

type ProcessFailedMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProcessFailedMessagesResponse) Reset() {
	*x = ProcessFailedMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessFailedMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFailedMessagesResponse) ProtoMessage() {}

func (x *ProcessFailedMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFailedMessagesResponse.ProtoReflect.Descriptor instead.
func (*ProcessFailedMessagesResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{14}
}

type GetFailedMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFailedMessagesRequest) Reset() {
	*x = GetFailedMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFailedMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFailedMessagesRequest) ProtoMessage() {}

func (x *GetFailedMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFailedMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetFailedMessagesRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{15}
}

type GetFailedMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Int32Value используется, что Google Protobuf не затирал нулевые значения
	CountRemaining *wrappers.Int32Value `protobuf:"bytes,1,opt,name=CountRemaining,proto3" json:"CountRemaining,omitempty"`
}

func (x *GetFailedMessagesResponse) Reset() {
	*x = GetFailedMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFailedMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFailedMessagesResponse) ProtoMessage() {}

func (x *GetFailedMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFailedMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetFailedMessagesResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{16}
}

func (x *GetFailedMessagesResponse) GetCountRemaining() *wrappers.Int32Value {
	if x != nil {
		return x.CountRemaining
	}
	return nil
}

type ShopGroupModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	FiasId string `protobuf:"bytes,2,opt,name=fiasId,proto3" json:"fiasId,omitempty"`
}

func (x *ShopGroupModel) Reset() {
	*x = ShopGroupModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopGroupModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopGroupModel) ProtoMessage() {}

func (x *ShopGroupModel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopGroupModel.ProtoReflect.Descriptor instead.
func (*ShopGroupModel) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{17}
}

func (x *ShopGroupModel) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShopGroupModel) GetFiasId() string {
	if x != nil {
		return x.FiasId
	}
	return ""
}

type ShopModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ShopModel) Reset() {
	*x = ShopModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopModel) ProtoMessage() {}

func (x *ShopModel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopModel.ProtoReflect.Descriptor instead.
func (*ShopModel) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{18}
}

func (x *ShopModel) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetShopGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConsumerCode    string   `protobuf:"bytes,1,opt,name=consumerCode,proto3" json:"consumerCode,omitempty"`
	ShopGroupCodes  []string `protobuf:"bytes,2,rep,name=shopGroupCodes,proto3" json:"shopGroupCodes,omitempty"`
	FiasIds         []string `protobuf:"bytes,3,rep,name=fiasIds,proto3" json:"fiasIds,omitempty"`
	ConsumerVersion string   `protobuf:"bytes,4,opt,name=consumerVersion,proto3" json:"consumerVersion,omitempty"`
}

func (x *GetShopGroupsRequest) Reset() {
	*x = GetShopGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopGroupsRequest) ProtoMessage() {}

func (x *GetShopGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetShopGroupsRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{19}
}

func (x *GetShopGroupsRequest) GetConsumerCode() string {
	if x != nil {
		return x.ConsumerCode
	}
	return ""
}

func (x *GetShopGroupsRequest) GetShopGroupCodes() []string {
	if x != nil {
		return x.ShopGroupCodes
	}
	return nil
}

func (x *GetShopGroupsRequest) GetFiasIds() []string {
	if x != nil {
		return x.FiasIds
	}
	return nil
}

func (x *GetShopGroupsRequest) GetConsumerVersion() string {
	if x != nil {
		return x.ConsumerVersion
	}
	return ""
}

type GetShopGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ShopGroupModel `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetShopGroupsResponse) Reset() {
	*x = GetShopGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopGroupsResponse) ProtoMessage() {}

func (x *GetShopGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetShopGroupsResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{20}
}

func (x *GetShopGroupsResponse) GetItems() []*ShopGroupModel {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetAllShopGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsShopGroupActive bool   `protobuf:"varint,1,opt,name=isShopGroupActive,proto3" json:"isShopGroupActive,omitempty"`
	LastShopGroupCode string `protobuf:"bytes,2,opt,name=lastShopGroupCode,proto3" json:"lastShopGroupCode,omitempty"`
	Limit             int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetAllShopGroupsRequest) Reset() {
	*x = GetAllShopGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllShopGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllShopGroupsRequest) ProtoMessage() {}

func (x *GetAllShopGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllShopGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetAllShopGroupsRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{21}
}

func (x *GetAllShopGroupsRequest) GetIsShopGroupActive() bool {
	if x != nil {
		return x.IsShopGroupActive
	}
	return false
}

func (x *GetAllShopGroupsRequest) GetLastShopGroupCode() string {
	if x != nil {
		return x.LastShopGroupCode
	}
	return ""
}

func (x *GetAllShopGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAllShopGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*AllShopGroup `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetAllShopGroupsResponse) Reset() {
	*x = GetAllShopGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllShopGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllShopGroupsResponse) ProtoMessage() {}

func (x *GetAllShopGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllShopGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetAllShopGroupsResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{22}
}

func (x *GetAllShopGroupsResponse) GetItems() []*AllShopGroup {
	if x != nil {
		return x.Items
	}
	return nil
}

type AllShopGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	IsActive  bool     `protobuf:"varint,2,opt,name=isActive,proto3" json:"isActive,omitempty"`
	IsDistr   bool     `protobuf:"varint,3,opt,name=isDistr,proto3" json:"isDistr,omitempty"`
	ShopCodes []string `protobuf:"bytes,4,rep,name=shopCodes,proto3" json:"shopCodes,omitempty"`
}

func (x *AllShopGroup) Reset() {
	*x = AllShopGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllShopGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllShopGroup) ProtoMessage() {}

func (x *AllShopGroup) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllShopGroup.ProtoReflect.Descriptor instead.
func (*AllShopGroup) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{23}
}

func (x *AllShopGroup) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AllShopGroup) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *AllShopGroup) GetIsDistr() bool {
	if x != nil {
		return x.IsDistr
	}
	return false
}

func (x *AllShopGroup) GetShopCodes() []string {
	if x != nil {
		return x.ShopCodes
	}
	return nil
}

type GetShopsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopGroupCode string `protobuf:"bytes,1,opt,name=shopGroupCode,proto3" json:"shopGroupCode,omitempty"`
}

func (x *GetShopsRequest) Reset() {
	*x = GetShopsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopsRequest) ProtoMessage() {}

func (x *GetShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopsRequest.ProtoReflect.Descriptor instead.
func (*GetShopsRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{24}
}

func (x *GetShopsRequest) GetShopGroupCode() string {
	if x != nil {
		return x.ShopGroupCode
	}
	return ""
}

type GetShopsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ShopModel `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetShopsResponse) Reset() {
	*x = GetShopsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopsResponse) ProtoMessage() {}

func (x *GetShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopsResponse.ProtoReflect.Descriptor instead.
func (*GetShopsResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{25}
}

func (x *GetShopsResponse) GetItems() []*ShopModel {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetShopGroupByShopGroupCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopGroupCode string `protobuf:"bytes,1,opt,name=shopGroupCode,proto3" json:"shopGroupCode,omitempty"`
}

func (x *GetShopGroupByShopGroupCodeRequest) Reset() {
	*x = GetShopGroupByShopGroupCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopGroupByShopGroupCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopGroupByShopGroupCodeRequest) ProtoMessage() {}

func (x *GetShopGroupByShopGroupCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopGroupByShopGroupCodeRequest.ProtoReflect.Descriptor instead.
func (*GetShopGroupByShopGroupCodeRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{26}
}

func (x *GetShopGroupByShopGroupCodeRequest) GetShopGroupCode() string {
	if x != nil {
		return x.ShopGroupCode
	}
	return ""
}

type GetShopGroupByShopGroupCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *ShopGroupModel `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *GetShopGroupByShopGroupCodeResponse) Reset() {
	*x = GetShopGroupByShopGroupCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopGroupByShopGroupCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopGroupByShopGroupCodeResponse) ProtoMessage() {}

func (x *GetShopGroupByShopGroupCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecom_shop_group_service_v1_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopGroupByShopGroupCodeResponse.ProtoReflect.Descriptor instead.
func (*GetShopGroupByShopGroupCodeResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP(), []int{27}
}

func (x *GetShopGroupByShopGroupCodeResponse) GetItem() *ShopGroupModel {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_v1_ecom_shop_group_service_v1_proto protoreflect.FileDescriptor

var file_v1_ecom_shop_group_service_v1_proto_rawDesc = []byte{
	0x0a, 0x23, 0x76, 0x31, 0x2f, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x87, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x42, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x66, 0x58, 0x6d, 0x6c, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x55, 0x66, 0x58, 0x6d, 0x6c, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x1e, 0x47,
	0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x53, 0x68, 0x6f,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x46, 0x69, 0x61, 0x73,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x69, 0x61,
	0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x46, 0x69, 0x61, 0x73, 0x49,
	0x64, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0xa9, 0x01, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x42, 0x79, 0x46, 0x69, 0x61, 0x73, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x4d, 0x0a, 0x0f,
	0x45, 0x52, 0x52, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x12,
	0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f,
	0x55, 0x4e, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x22, 0x81, 0x01, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x53,
	0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x52, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x22,
	0x43, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x73, 0x22, 0x55, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x05, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x65, 0x63, 0x6f, 0x6d,
	0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x7f, 0x0a, 0x11, 0x49,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x73, 0x12, 0x2c,
	0x0a, 0x11, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x54, 0x6f, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x53, 0x68, 0x6f, 0x70, 0x73,
	0x54, 0x6f, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x14, 0x0a, 0x12,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x7c, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x68, 0x6f, 0x70, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x54, 0x6f, 0x53, 0x68,
	0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x53, 0x68, 0x6f, 0x70, 0x73, 0x54, 0x6f, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x22, 0x5c, 0x0a, 0x1c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x56, 0x69, 0x72,
	0x74, 0x75, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3c, 0x0a, 0x19, 0x49, 0x73, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4f, 0x6e, 0x6c,
	0x79, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x19, 0x49, 0x73, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4f, 0x6e,
	0x6c, 0x79, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22,
	0x1f, 0x0a, 0x1d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x5c, 0x0a, 0x1c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x1f,
	0x0a, 0x1d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x60, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0e, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x3c, 0x0a,
	0x0e, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x61, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x61, 0x73, 0x49, 0x64, 0x22, 0x1f, 0x0a, 0x09, 0x53,
	0x68, 0x6f, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xa6, 0x01, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x68, 0x6f,
	0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0e, 0x73, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x61, 0x73, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x61, 0x73, 0x49, 0x64, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x63,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x59, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e,
	0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x8b, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11,
	0x69, 0x73, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x69, 0x73, 0x53, 0x68, 0x6f, 0x70, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x6c, 0x61,
	0x73, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x5a,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x65, 0x63, 0x6f, 0x6d,
	0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x76, 0x0a, 0x0c, 0x41, 0x6c,
	0x6c, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73,
	0x44, 0x69, 0x73, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x43, 0x6f, 0x64,
	0x65, 0x73, 0x22, 0x37, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x68,
	0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x4f, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25,
	0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x4a, 0x0a, 0x22,
	0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x53, 0x68,
	0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x68, 0x6f, 0x70, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xb4, 0x01, 0x0a, 0x23, 0x47, 0x65, 0x74,
	0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3e, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a,
	0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d,
	0x22, 0x4d, 0x0a, 0x0f, 0x45, 0x52, 0x52, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x52, 0x45, 0x41,
	0x53, 0x4f, 0x4e, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x4f,
	0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x32,
	0xa8, 0x0c, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x91, 0x01,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79,
	0x53, 0x68, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x39, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x42, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x3a, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x53,
	0x68, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x8b, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x42, 0x79, 0x46, 0x69, 0x61, 0x73, 0x49, 0x64, 0x12, 0x37, 0x2e, 0x65, 0x63, 0x6f,
	0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x46, 0x69, 0x61, 0x73, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x38, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x46,
	0x69, 0x61, 0x73, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x79, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x53, 0x68,
	0x6f, 0x70, 0x73, 0x12, 0x33, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x06, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x29, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2a, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12,
	0x6d, 0x0a, 0x0a, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2d, 0x2e,
	0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x65,
	0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x8e,
	0x01, 0x0a, 0x15, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x38, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x56, 0x69,
	0x72, 0x74, 0x75, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x39, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x8e, 0x01, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x38, 0x2e, 0x65, 0x63, 0x6f, 0x6d,
	0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x39, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x82, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x34, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68,
	0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x65,
	0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x76, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x30, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68,
	0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7f, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x12, 0x33, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x68,
	0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x12, 0x2b, 0x2e, 0x65, 0x63, 0x6f,
	0x6d, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73,
	0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0xa0, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x53,
	0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x3e, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73,
	0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x42, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3f, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x73,
	0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x42, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4c, 0x5a, 0x19, 0x2f, 0x73,
	0x68, 0x6f, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x73, 0x5f, 0x76, 0x31, 0xca, 0x02, 0x13, 0x53, 0x68, 0x6f, 0x70, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x5c, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x5c, 0x76, 0x31, 0xe2, 0x02, 0x18,
	0x53, 0x68, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x5c, 0x53, 0x68, 0x6f, 0x70, 0x73,
	0x5c, 0x76, 0x31, 0x5c, 0x4d, 0x65, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_ecom_shop_group_service_v1_proto_rawDescOnce sync.Once
	file_v1_ecom_shop_group_service_v1_proto_rawDescData = file_v1_ecom_shop_group_service_v1_proto_rawDesc
)

func file_v1_ecom_shop_group_service_v1_proto_rawDescGZIP() []byte {
	file_v1_ecom_shop_group_service_v1_proto_rawDescOnce.Do(func() {
		file_v1_ecom_shop_group_service_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_ecom_shop_group_service_v1_proto_rawDescData)
	})
	return file_v1_ecom_shop_group_service_v1_proto_rawDescData
}

var file_v1_ecom_shop_group_service_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_ecom_shop_group_service_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_v1_ecom_shop_group_service_v1_proto_goTypes = []interface{}{
	(GetShopGroupByFiasIdResponse_ERR_INFO_REASON)(0),        // 0: ecom.shop_group_service.v1.GetShopGroupByFiasIdResponse.ERR_INFO_REASON
	(GetShopGroupByShopGroupCodeResponse_ERR_INFO_REASON)(0), // 1: ecom.shop_group_service.v1.GetShopGroupByShopGroupCodeResponse.ERR_INFO_REASON
	(*GetShopGroupByShopCodeRequest)(nil),                    // 2: ecom.shop_group_service.v1.GetShopGroupByShopCodeRequest
	(*GetShopGroupByShopCodeResponse)(nil),                   // 3: ecom.shop_group_service.v1.GetShopGroupByShopCodeResponse
	(*GetShopGroupByFiasIdRequest)(nil),                      // 4: ecom.shop_group_service.v1.GetShopGroupByFiasIdRequest
	(*GetShopGroupByFiasIdResponse)(nil),                     // 5: ecom.shop_group_service.v1.GetShopGroupByFiasIdResponse
	(*GetConsumerShopsRequest)(nil),                          // 6: ecom.shop_group_service.v1.GetConsumerShopsRequest
	(*ShopGroupItem)(nil),                                    // 7: ecom.shop_group_service.v1.ShopGroupItem
	(*ShopGroupsResponse)(nil),                               // 8: ecom.shop_group_service.v1.ShopGroupsResponse
	(*ImportFileRequest)(nil),                                // 9: ecom.shop_group_service.v1.ImportFileRequest
	(*ImportFileResponse)(nil),                               // 10: ecom.shop_group_service.v1.ImportFileResponse
	(*ExportRequest)(nil),                                    // 11: ecom.shop_group_service.v1.ExportRequest
	(*ExportResponse)(nil),                                   // 12: ecom.shop_group_service.v1.ExportResponse
	(*GenerateVirtualGroupsRequest)(nil),                     // 13: ecom.shop_group_service.v1.GenerateVirtualGroupsRequest
	(*GenerateVirtualGroupsResponse)(nil),                    // 14: ecom.shop_group_service.v1.GenerateVirtualGroupsResponse
	(*ProcessFailedMessagesRequest)(nil),                     // 15: ecom.shop_group_service.v1.ProcessFailedMessagesRequest
	(*ProcessFailedMessagesResponse)(nil),                    // 16: ecom.shop_group_service.v1.ProcessFailedMessagesResponse
	(*GetFailedMessagesRequest)(nil),                         // 17: ecom.shop_group_service.v1.GetFailedMessagesRequest
	(*GetFailedMessagesResponse)(nil),                        // 18: ecom.shop_group_service.v1.GetFailedMessagesResponse
	(*ShopGroupModel)(nil),                                   // 19: ecom.shop_group_service.v1.ShopGroupModel
	(*ShopModel)(nil),                                        // 20: ecom.shop_group_service.v1.ShopModel
	(*GetShopGroupsRequest)(nil),                             // 21: ecom.shop_group_service.v1.GetShopGroupsRequest
	(*GetShopGroupsResponse)(nil),                            // 22: ecom.shop_group_service.v1.GetShopGroupsResponse
	(*GetAllShopGroupsRequest)(nil),                          // 23: ecom.shop_group_service.v1.GetAllShopGroupsRequest
	(*GetAllShopGroupsResponse)(nil),                         // 24: ecom.shop_group_service.v1.GetAllShopGroupsResponse
	(*AllShopGroup)(nil),                                     // 25: ecom.shop_group_service.v1.AllShopGroup
	(*GetShopsRequest)(nil),                                  // 26: ecom.shop_group_service.v1.GetShopsRequest
	(*GetShopsResponse)(nil),                                 // 27: ecom.shop_group_service.v1.GetShopsResponse
	(*GetShopGroupByShopGroupCodeRequest)(nil),               // 28: ecom.shop_group_service.v1.GetShopGroupByShopGroupCodeRequest
	(*GetShopGroupByShopGroupCodeResponse)(nil),              // 29: ecom.shop_group_service.v1.GetShopGroupByShopGroupCodeResponse
	(*wrappers.Int32Value)(nil),                              // 30: google.protobuf.Int32Value
}
var file_v1_ecom_shop_group_service_v1_proto_depIdxs = []int32{
	7,  // 0: ecom.shop_group_service.v1.ShopGroupsResponse.Items:type_name -> ecom.shop_group_service.v1.ShopGroupItem
	30, // 1: ecom.shop_group_service.v1.GetFailedMessagesResponse.CountRemaining:type_name -> google.protobuf.Int32Value
	19, // 2: ecom.shop_group_service.v1.GetShopGroupsResponse.items:type_name -> ecom.shop_group_service.v1.ShopGroupModel
	25, // 3: ecom.shop_group_service.v1.GetAllShopGroupsResponse.items:type_name -> ecom.shop_group_service.v1.AllShopGroup
	20, // 4: ecom.shop_group_service.v1.GetShopsResponse.items:type_name -> ecom.shop_group_service.v1.ShopModel
	19, // 5: ecom.shop_group_service.v1.GetShopGroupByShopGroupCodeResponse.item:type_name -> ecom.shop_group_service.v1.ShopGroupModel
	2,  // 6: ecom.shop_group_service.v1.ShopGroup.GetShopGroupByShopCode:input_type -> ecom.shop_group_service.v1.GetShopGroupByShopCodeRequest
	4,  // 7: ecom.shop_group_service.v1.ShopGroup.GetShopGroupByFiasId:input_type -> ecom.shop_group_service.v1.GetShopGroupByFiasIdRequest
	6,  // 8: ecom.shop_group_service.v1.ShopGroup.GetConsumerShops:input_type -> ecom.shop_group_service.v1.GetConsumerShopsRequest
	11, // 9: ecom.shop_group_service.v1.ShopGroup.Export:input_type -> ecom.shop_group_service.v1.ExportRequest
	9,  // 10: ecom.shop_group_service.v1.ShopGroup.ImportFile:input_type -> ecom.shop_group_service.v1.ImportFileRequest
	13, // 11: ecom.shop_group_service.v1.ShopGroup.GenerateVirtualGroups:input_type -> ecom.shop_group_service.v1.GenerateVirtualGroupsRequest
	15, // 12: ecom.shop_group_service.v1.ShopGroup.ProcessFailedMessages:input_type -> ecom.shop_group_service.v1.ProcessFailedMessagesRequest
	17, // 13: ecom.shop_group_service.v1.ShopGroup.GetFailedMessages:input_type -> ecom.shop_group_service.v1.GetFailedMessagesRequest
	21, // 14: ecom.shop_group_service.v1.ShopGroup.GetShopGroups:input_type -> ecom.shop_group_service.v1.GetShopGroupsRequest
	23, // 15: ecom.shop_group_service.v1.ShopGroup.GetAllShopGroups:input_type -> ecom.shop_group_service.v1.GetAllShopGroupsRequest
	26, // 16: ecom.shop_group_service.v1.ShopGroup.GetShops:input_type -> ecom.shop_group_service.v1.GetShopsRequest
	28, // 17: ecom.shop_group_service.v1.ShopGroup.GetShopGroupByShopGroupCode:input_type -> ecom.shop_group_service.v1.GetShopGroupByShopGroupCodeRequest
	3,  // 18: ecom.shop_group_service.v1.ShopGroup.GetShopGroupByShopCode:output_type -> ecom.shop_group_service.v1.GetShopGroupByShopCodeResponse
	5,  // 19: ecom.shop_group_service.v1.ShopGroup.GetShopGroupByFiasId:output_type -> ecom.shop_group_service.v1.GetShopGroupByFiasIdResponse
	8,  // 20: ecom.shop_group_service.v1.ShopGroup.GetConsumerShops:output_type -> ecom.shop_group_service.v1.ShopGroupsResponse
	12, // 21: ecom.shop_group_service.v1.ShopGroup.Export:output_type -> ecom.shop_group_service.v1.ExportResponse
	10, // 22: ecom.shop_group_service.v1.ShopGroup.ImportFile:output_type -> ecom.shop_group_service.v1.ImportFileResponse
	14, // 23: ecom.shop_group_service.v1.ShopGroup.GenerateVirtualGroups:output_type -> ecom.shop_group_service.v1.GenerateVirtualGroupsResponse
	16, // 24: ecom.shop_group_service.v1.ShopGroup.ProcessFailedMessages:output_type -> ecom.shop_group_service.v1.ProcessFailedMessagesResponse
	18, // 25: ecom.shop_group_service.v1.ShopGroup.GetFailedMessages:output_type -> ecom.shop_group_service.v1.GetFailedMessagesResponse
	22, // 26: ecom.shop_group_service.v1.ShopGroup.GetShopGroups:output_type -> ecom.shop_group_service.v1.GetShopGroupsResponse
	24, // 27: ecom.shop_group_service.v1.ShopGroup.GetAllShopGroups:output_type -> ecom.shop_group_service.v1.GetAllShopGroupsResponse
	27, // 28: ecom.shop_group_service.v1.ShopGroup.GetShops:output_type -> ecom.shop_group_service.v1.GetShopsResponse
	29, // 29: ecom.shop_group_service.v1.ShopGroup.GetShopGroupByShopGroupCode:output_type -> ecom.shop_group_service.v1.GetShopGroupByShopGroupCodeResponse
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_ecom_shop_group_service_v1_proto_init() }
func file_v1_ecom_shop_group_service_v1_proto_init() {
	if File_v1_ecom_shop_group_service_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopGroupByShopCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopGroupByShopCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopGroupByFiasIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopGroupByFiasIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConsumerShopsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopGroupItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateVirtualGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateVirtualGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessFailedMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessFailedMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFailedMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFailedMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopGroupModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllShopGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllShopGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllShopGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopGroupByShopGroupCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ecom_shop_group_service_v1_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopGroupByShopGroupCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_ecom_shop_group_service_v1_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_ecom_shop_group_service_v1_proto_goTypes,
		DependencyIndexes: file_v1_ecom_shop_group_service_v1_proto_depIdxs,
		EnumInfos:         file_v1_ecom_shop_group_service_v1_proto_enumTypes,
		MessageInfos:      file_v1_ecom_shop_group_service_v1_proto_msgTypes,
	}.Build()
	File_v1_ecom_shop_group_service_v1_proto = out.File
	file_v1_ecom_shop_group_service_v1_proto_rawDesc = nil
	file_v1_ecom_shop_group_service_v1_proto_goTypes = nil
	file_v1_ecom_shop_group_service_v1_proto_depIdxs = nil
}
