<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/echo.v1.proto

namespace ShopGroups\EchoService\v1\Meta;

class EchoV1
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8a020a1076312f6563686f2e76312e70726f746f12076563686f2e7631" .
            "221e0a0b4563686f52657175657374120f0a074d65737361676518012001" .
            "2809221f0a0c4563686f526573706f6e7365120f0a074d65737361676518" .
            "0120012809324a0a0b4563686f53657276696365123b0a0a4563686f4d65" .
            "74686f6412142e6563686f2e76312e4563686f526571756573741a152e65" .
            "63686f2e76312e4563686f526573706f6e7365220042585a192f73686f70" .
            "5f67726f7570735f636f6e7472616374735f7631ca021953686f7047726f" .
            "7570735c4563686f536572766963655c7631e2021e53686f7047726f7570" .
            "735c4563686f536572766963655c76315c4d657461620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

